// Generated by scripts/write_catalogue_versions.py. Do not edit manually.
export const miniCatalogueVersion = "2951540f0f87b739";
export const metalsCatalogueVersion = "60847c042b2f2094";

export const miniCatalogueUrl =
  `/catalogue/mini-catalogue.pdf?v=${miniCatalogueVersion}`;
export const metalsCatalogueUrl =
  `/catalogue/metals-catalogue.pdf?v=${metalsCatalogueVersion}`;
