// Generated by scripts/write_catalogue_versions.py. Do not edit manually.
export const miniCatalogueVersion = "904e991d027c5d0a";
export const metalsCatalogueVersion = "7a0b47f940cff219";

export const miniCatalogueUrl =
  `/catalogue/mini-catalogue.pdf?v=${miniCatalogueVersion}`;
export const metalsCatalogueUrl =
  `/catalogue/metals-catalogue.pdf?v=${metalsCatalogueVersion}`;
