// Generated by scripts/write_catalogue_versions.py. Do not edit manually.
export const miniCatalogueVersion = "f94acb8de504d0c5";
export const metalsCatalogueVersion = "1ecaaa2681c63f7e";

export const miniCatalogueUrl =
  `/catalogue/mini-catalogue.pdf?v=${miniCatalogueVersion}`;
export const metalsCatalogueUrl =
  `/catalogue/metals-catalogue.pdf?v=${metalsCatalogueVersion}`;
