// AUTO-GENERATED by scripts/regen_website_data.py — DO NOT EDIT BY HAND
// Source:    data-source/featured-work.json (+ data-source/featured-images/)
// Generated: 2026-04-30T22:13:03.607423Z
// Re-run:    npm run sync-data

export type FeaturedWork = {
  id: string;
  title: string;
  description: string;
  tag: string;
  year: number;
  category: string;
  fullStory: string;
  imagePath: string | null;  // null = no image, page falls back to placeholder
  priceExVat: number | null;
  hideExVat: boolean;
};

export const featuredWork: FeaturedWork[] = [];
