const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const projectRoot = path.resolve(__dirname, "..");
const packageJson = JSON.parse(fs.readFileSync(path.join(projectRoot, "package.json"), "utf8"));

const expectedDailySync =
  "npm run sync-data && npm run sync-excel && npm run export-pdfs && npm run version-catalogues && npm run validate-sync";

assert.equal(
  packageJson.scripts?.["daily-sync"],
  expectedDailySync,
  "daily-sync changed; review generated-file boundaries before publishing"
);

const generatedFiles = [
  "lib/mini-data.ts",
  "lib/metals-data.ts",
  "lib/featured-data.ts",
  "lib/catalogue-versions.ts",
];

for (const relativePath of generatedFiles) {
  const source = fs.readFileSync(path.join(projectRoot, relativePath), "utf8");
  assert.match(
    source.slice(0, 180),
    /AUTO-GENERATED|Generated by scripts/,
    `${relativePath} must keep a generated-file header`
  );
}

const generatedScriptSources = [
  "scripts/regen_website_data.py",
  "scripts/write_catalogue_versions.py",
  "scripts/phase2/sync_phase2.py",
];

const forbiddenAppWriteTargets = [
  "app/",
  "app\\",
  "OrdersClient",
  "quote-email",
  "order-accounting",
  "payment-settings",
];

for (const relativePath of generatedScriptSources) {
  const source = fs.readFileSync(path.join(projectRoot, relativePath), "utf8");
  for (const forbidden of forbiddenAppWriteTargets) {
    assert.equal(
      source.includes(forbidden),
      false,
      `${relativePath} mentions ${forbidden}; review before allowing daily sync to touch app code`
    );
  }
}

const setupScript = fs.readFileSync(
  path.join(projectRoot, "scripts/setup/Setup-Owner-Machine.ps1"),
  "utf8"
);

assert.match(
  setupScript,
  /Unstage-NonGeneratedGitChanges/,
  "owner daily sync wrapper must unstage non-generated website changes without blocking catalogue sync"
);
assert.match(
  setupScript,
  /Daily sync post-refresh/,
  "owner daily sync wrapper must inspect changed paths after regenerating catalogue outputs"
);
assert.match(
  setupScript,
  /will be left unstaged and will not be published by daily sync/,
  "owner daily sync wrapper must log unexpected website-code changes instead of silently publishing them"
);
assert.match(
  setupScript,
  /git add lib\/mini-data\.ts lib\/metals-data\.ts lib\/featured-data\.ts lib\/catalogue-versions\.ts/,
  "owner daily sync wrapper must stage every generated catalogue data file explicitly"
);

console.log("ok - daily sync boundaries are limited to documented generated catalogue outputs");
