#!/usr/bin/env python3
"""Write cache-busting catalogue URLs from the generated PDF contents."""

from __future__ import annotations

import hashlib
from pathlib import Path


HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent
OUTPUT = PROJECT_ROOT / "lib" / "catalogue-versions.ts"

CATALOGUES = {
    "mini": PROJECT_ROOT / "public" / "catalogue" / "mini-catalogue.pdf",
    "metals": PROJECT_ROOT / "public" / "catalogue" / "metals-catalogue.pdf",
}


def version(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"Catalogue PDF does not exist: {path}")
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def main() -> None:
    mini_version = version(CATALOGUES["mini"])
    metals_version = version(CATALOGUES["metals"])
    source = f"""// Generated by scripts/write_catalogue_versions.py. Do not edit manually.
export const miniCatalogueVersion = "{mini_version}";
export const metalsCatalogueVersion = "{metals_version}";

export const miniCatalogueUrl =
  `/catalogue/mini-catalogue.pdf?v=${{miniCatalogueVersion}}`;
export const metalsCatalogueUrl =
  `/catalogue/metals-catalogue.pdf?v=${{metalsCatalogueVersion}}`;
"""
    OUTPUT.write_text(source, encoding="utf-8")
    print(f"  OK Mini catalogue version: {mini_version}")
    print(f"  OK Metals catalogue version: {metals_version}")


if __name__ == "__main__":
    main()
